/*
 * Showcase configuration
 *
 * Add a new entry using the library id from app.js. Libraries without an
 * entry intentionally render the "No Showcase" state.
 */
const showcaseTable = Object.freeze({
  armenta_lib: {
    embedUrl: 'https://mega.nz/embed/MRkRBApL#KFE30TjcbNAfCv-aY8FJSjKAxzEM_eU_6zvRJSydwms'
  },
  discord_lib: {
    embedUrl: 'https://mega.nz/embed/dFtFBS4a#Rm0HKEYLSmSK7Udwy-UzKmTn4VKPekEsL8KAB0niaSo'
  },
  synergyui: {
    embedUrl: 'https://mega.nz/embed/9UdzlJbD#cbWE8v9-Q59CtYhD0zLPXjO7kCMSAROYCUA4SE2seH0'
  }
});

function getShowcase(libraryId) {
  return showcaseTable[libraryId] || null;
}

window.showcaseTable = showcaseTable;
window.getShowcase = getShowcase;

// To add another showcase, add one row above:
// another_library_id: { embedUrl: 'https://mega.nz/embed/...' }

/*
 * The corresponding HTML embed is intentionally generated by the shelf so
 * the configuration stays a single URL per library:
 *
 * <iframe width="640" height="360" frameborder="0"
 *   src="https://mega.nz/embed/..." allowfullscreen></iframe>
 */

// Keep the helper available to app.js without exposing extra global state.
void window.showcaseTable;
void window.getShowcase;

